### PR TITLE
Add help descriptions and aliases to argparse

### PR DESCRIPTION
**Pull request by AnthonyDiGirolamo**
What do you think? Sample help:

```
./khef.py
usage: khef [-h]
            {init,tet-list,list,tet-add,add,tet-break,break,send,read} ...

share secrets with your Ka-tet

positional arguments:
  {init,tet-list,list,tet-add,add,tet-break,break,send,read}
                        subcommands
    init                Configure khef for your system Creates the user's
                        ~/.config/khef directory. This subcommand must be
                        run before any other khef subcommands are invoked;
                        most of them assume that the ~/.config/khef
                        directory exists and has been correctly configured.
    tet-list (list)     List members of your Ka-tet Lists any OpenSSH pubkey
                        files already installed in the user's ~/.config/khef
                        directory.
    tet-add (add)       Add a new Ka-mate. Download a collection of OpenSSH
                        public keys from GitHub and install them into the
                        user's ~/.config/khef directory.
    tet-break (break)   Break your Ka-tet. Remove existing public keys from
                        ~/.config/khef
    send                send a message to your Ka-tet. Writes a file to the
                        shared khef directory, signing the results. Using
                        this subcommand ensures that any file written to
                        shared storage is signed and therefore verifiable by
                        others.
    read                Verify and print a message. Attempts to validate the
                        authenticity of a shared message, printing its
                        content to stdout on success. Using this subcommand
                        ensures that unverifiable files are not read by
                        users.

options:
  -h, --help            show this help message and exit
```

### CODE REVIEW

**Comment by robertdfrench** [comment]
This is really tempting! It's clever, no doubt. I think I'm hung up on three things:

* You and I know that Python has two forms of comments, but newcomers don't and it confuses them. It confused me and Bill once at the lab.
* This works for the subcommand descriptions, but not for the subcommand argument descriptions (but see below). So an auditor would need to understand two patterns for including things in the "help" output.
* I think (and this is my fault) this further blurs the distinction between "documentation for the user" and "documentation for the auditor / developer". That line barely exists right now and needs to be clarified; my *intent* is for `khef --help` to print things that are good for the user to read, and for the source code comments to contain things that are good for an auditor to read.

---

Alternatively, we could double down on this approach and go hog wild on types. Sortof like this:

```python3
class GithubUsername(str):                                                       
    """Your username on github.com"""                                            
    pass                                                                         
                                                                                 
class SSHIdentity(Path):                                                         
    """Path to your OpenSSH public key"""                                        
    pass                                                                         

class SharedKhef(Path):
    """Path to your shared khef directory"""
    pass
                                                                                 
def main:                                                                        
    # blah blah                                                                  
    def init(args):                                                              
        """                                                                      
        Creates the user's ~/.config/khef directory. This subcommand must be     
        run before any other khef subcommands are invoked; most of them assume   
        that the ~/.config/khef directory exists and has been correctly          
        configured.                                                              
        """                                                                      
        make_github_username(args.github_username)                               
        make_ssh_identity(args.ssh_identity)                                     
        make_shared_khef(args.shared_khef)                                       
                                                                                 
    sp = subparsers.add_parser('init', init.__doc__)                             
    sp.add_argument('--github-username', required=True, help=GithubUsername.__doc__, type=GithubUsername)
    sp.add_argument('--ssh-identity', required=True, help=SSHIdentity.__doc__, type=SSHIdentity)
``` 

If we wanted to get *totally nuts* with this approach, we could do something like this:

```python3
class Subcommand:
    pass

class Init(Subcommand):
    """ Creates the user's ~/.config/khef directory """
    github_username: GithubUsername
    ssh_identity: SSHIdentity
    shared_khef: SharedKhef

    def __call__(self):
        make_github_username(self.github_username)                               
        make_ssh_identity(self.ssh_identity)                                     
        make_shared_khef(self.shared_khef)   
```

This would allow us to query all subclasses of `Subcommand` at runtime, and then deduce their arguments by looking at their `.__annotations__` property (in this case, `Init.__annotations__` would be a dict containing the three variable names as keys, and their types as values). We could go so far as to construct subcommands and subcommand arguments dynamically, but I worry that would be *too clever to audit*.

**Comment by robertdfrench** [comment]
Like this:

```python3
#!/usr/bin/python3
from argparse import ArgumentParser
from pathlib import Path

class GithubUsername(str):
    """Your username on GitHubDotCom"""
    pass

class SSHIdentity(Path):
    """The path to your OpenSSH Public Key"""
    pass

class Subcommand:
    pass

class Sign(Subcommand):
    """Sign a file with your OpenSSH key"""
    file: Path
    pubkey: SSHIdentity

    def __call__(self):
        print(f"sign {self.file} and {self.pubkey}")

class Verify(Subcommand):
    """Verify an alleged message"""
    username: GithubUsername
    file: Path

    def __call__(self):
        print(f"verify {self.username} and {self.file}")

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.set_defaults(func=lambda args: parser.print_help())
    subparsers = parser.add_subparsers(help="subcommands")
    for subcommand in Subcommand.__subclasses__():
        sp = subparsers.add_parser(subcommand.__name__.lower(),
                help=subcommand.__doc__)
        for argument,argtype in subcommand.__annotations__.items():
            sp.add_argument(argument, type=argtype, help=argtype.__doc__)
    args = parser.parse_args()
    args.func(args)
```

**Comment by robertdfrench** [comment]
FYI, above produces this kind of output:

```console
$ ./uix.py --help
usage: uix.py [-h] {sign,verify} ...

positional arguments:
  {sign,verify}  subcommands
    sign         Sign a file with your OpenSSH key
    verify       Verify an alleged message

optional arguments:
  -h, --help     show this help message and exit
$ ./uix.py verify --help
usage: uix.py verify [-h] username file

positional arguments:
  username    Your username on GitHubDotCom
  file        PurePath subclass that can make system calls. Path represents a
              filesystem path but unlike PurePath, also offers methods to do
              system calls on path objects. Depending on your system,
              instantiating a Path will return either a PosixPath or a
              WindowsPath object. You can also instantiate a PosixPath or
              WindowsPath directly, but cannot instantiate a WindowsPath on a
              POSIX system or vice versa.

optional arguments:
  -h, --help  show this help message and exit
```

Figuring out how to construct those types is a bit beyond me at the moment. And anyways, the code needed to produce this is already more complex than I want to do. I am really inclined to make this look as much like [the official argparse tutorial](https://docs.python.org/3.7/howto/argparse.html#id1) as possible, that way auditors do not have much to learn.

**Comment by robertdfrench** [comment]
@AnthonyDiGirolamo what do you think about ^ that stuff?

**Comment by AnthonyDiGirolamo** [comment]
Like you said it's complex and detracts from auditability. Did you want
something like it anyway?

**Comment by robertdfrench** [comment]
Nah, just wanted to make sure you knew I wasn't ignoring your PR, and also check to see if you were persuaded one way or the other. I'll close this.

**Pull request closed without merging**
